apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: fer.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fer-service
                port:
                  number: 80
