replicaCount: 2

image:
  repository: fer_app     # Change to DockerHub later: username/fer_app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  portFastAPI: 80
  portStreamlit: 8501

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"

env:
  SNOWFLAKE_USER: ""
  SNOWFLAKE_PASSWORD: ""
  SNOWFLAKE_ACCOUNT: ""
  SNOWFLAKE_DATABASE: "MLDB"
  SNOWFLAKE_SCHEMA: "PUBLIC"
  SNOWFLAKE_WAREHOUSE: "ML_WH"

ingress:
  enabled: false
  className: nginx
  host: fer.yourdomain.com

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
